### ISSUE TITLE
Create list of city zoning code locations

### ISSUE THREAD

**Issue by jridener** [opensmc/opensmc.github.io#13]
For a project with Sustainable San Mateo County, we need to scrape data from city zoning codes. The first step would be to create a list of urls where city zoning regulations can be found. This spreadsheet is here: https://docs.google.com/spreadsheets/d/199shxJaRycwVGXGR46jQNyur960dnPf-L7-lIcXyKRg/edit?usp=sharing

**Comment by verythorough** [comment]
This seems separate from the website project.  I'm going to cross-post it on the [Project Ideas repo](https://github.com/opensmc/project-ideas/issues), and maybe we should start a new repo specific to the project.  Sounds like a nice opportunity for data work.

**Comment by jridener** [comment]
Yes, thanks! I was trying to get things done too quickly and added it to
the website project repo. Thanks for cleaning up after me!

**Comment by verythorough** [comment]
:+1:
