### ISSUE TITLE
Add OpenSMC Facebook feed to homepage

### ISSUE THREAD

**Issue by ShellSV** [opensmc/opensmc.github.io#15]
https://www.facebook.com/opensmc

**Comment by verythorough** [comment]
1. Facebook feed widget builder here: https://developers.facebook.com/docs/plugins/page-plugin
2. Complete the following fields:
   - Page URL: https://www.facebook.com/opensmc
   - Tabs: timeline, events, messages
   - Width: 500
   - Height: 600?  We may adjust depending on how it fits on the page
   - Leave the default settings in the checkboxes
3. Check the sample and click Get Code
4. Copy the code from the first box and paste in `_includes/header.html` after the opening `<body>` tag, around line 25.
5. Copy the code from the second box and paste in `index.html` before the comment about adding a Twitter widget.  (You can remove this comment as well.)

**Comment by verythorough** [comment]
Closed by #18.
