### ISSUE TITLE
Add "More Issues" button to getstarted/index.html

### ISSUE THREAD

**Issue by verythorough** [opensmc/opensmc.github.io#2]
Add a button linking to our full issues listing (on Civic Tech Issue Finder) below the issues widget on the Get Started page.

**Comment by avemulkar** [comment]
Hi there,

Just opened a PR for this issue: https://github.com/opensmc/opensmc.github.io/pull/4.  Let me know if you would like me to make any changes. It's my first PR to this repo so I may have gotten the styling or formatting wrong!

Thanks!

**Comment by verythorough** [comment]
Closed by #4.  Thanks, @avemulkar!
