### ISSUE TITLE
Add what do you love about where you live form to check-in banner 

### ISSUE THREAD

**Issue by jridener** [opensmc/opensmc.github.io#8]
Replace the text in the check-in banner to say: "Tell us about what you love about your community" and link the button to https://docs.google.com/forms/d/1GZjLd63msklaPlvXecmzAzmiV17bbCOsu2MvGOcPfxI/viewform

The button can read "Tell us"

The banner can show all days except Tuesday.

**Comment by verythorough** [comment]
Closed by #9
